<?php

namespace App\Libraries;

class CountryCodes
{
	static $codes = [
	[ 'country' => "DZ", 'tel' => "213", 'name' => "Algeria" ],
	[ 'country' => "AD", 'tel' => "376", 'name' => "Andorra" ],
	[ 'country' => "AO", 'tel' => "244", 'name' => "Angola" ],
	[ 'country' => "AI", 'tel' => "1264", 'name' => "Anguilla" ],
	[ 'country' => "AG", 'tel' => "1268", 'name' => "Antigua & Barbuda" ],
	[ 'country' => "AR", 'tel' => "54", 'name' => "Argentina" ],
	[ 'country' => "AM", 'tel' => "374", 'name' => "Armenia" ],
	[ 'country' => "AW", 'tel' => "297", 'name' => "Aruba" ],
	[ 'country' => "AU", 'tel' => "61", 'name' => "Australia" ],
	[ 'country' => "AT", 'tel' => "43", 'name' => "Austria" ],
	[ 'country' => "AZ", 'tel' => "994", 'name' => "Azerbaijan" ],
	[ 'country' => "BS", 'tel' => "1242", 'name' => "Bahamas" ],
	[ 'country' => "BH", 'tel' => "973", 'name' => "Bahrain" ],
	[ 'country' => "BD", 'tel' => "880", 'name' => "Bangladesh" ],
	[ 'country' => "BB", 'tel' => "1246", 'name' => "Barbados" ],
	[ 'country' => "BY", 'tel' => "375", 'name' => "Belarus" ],
	[ 'country' => "BE", 'tel' => "32", 'name' => "Belgium" ],
	[ 'country' => "BZ", 'tel' => "501", 'name' => "Belize" ],
	[ 'country' => "BJ", 'tel' => "229", 'name' => "Benin" ],
	[ 'country' => "BM", 'tel' => "1441", 'name' => "Bermuda" ],
	[ 'country' => "BT", 'tel' => "975", 'name' => "Bhutan" ],
	[ 'country' => "BO", 'tel' => "591", 'name' => "Bolivia" ],
	[ 'country' => "BA", 'tel' => "387", 'name' => "Bosnia Herzegovina" ],
	[ 'country' => "BW", 'tel' => "267", 'name' => "Botswana" ],
	[ 'country' => "BR", 'tel' => "55", 'name' => "Brazil" ],
	[ 'country' => "BN", 'tel' => "673", 'name' => "Brunei" ],
	[ 'country' => "BG", 'tel' => "359", 'name' => "Bulgaria" ],
	[ 'country' => "BF", 'tel' => "226", 'name' => "Burkina Faso" ],
	[ 'country' => "BI", 'tel' => "257", 'name' => "Burundi" ],
	[ 'country' => "KH", 'tel' => "855", 'name' => "Cambodia" ],
	[ 'country' => "CM", 'tel' => "237", 'name' => "Cameroon" ],
	[ 'country' => "CA", 'tel' => "1", 'name' => "Canada" ],
	[ 'country' => "CV", 'tel' => "238", 'name' => "Cape Verde Islands" ],
	[ 'country' => "KY", 'tel' => "1345", 'name' => "Cayman Islands" ],
	[ 'country' => "CF", 'tel' => "236", 'name' => "Central African Republic" ],
	[ 'country' => "CL", 'tel' => "56", 'name' => "Chile" ],
	[ 'country' => "CN", 'tel' => "86", 'name' => "China" ],
	[ 'country' => "CO", 'tel' => "57", 'name' => "Colombia" ],
	[ 'country' => "KM", 'tel' => "269", 'name' => "Comoros" ],
	[ 'country' => "CG", 'tel' => "242", 'name' => "Congo" ],
	[ 'country' => "CK", 'tel' => "682", 'name' => "Cook Islands" ],
	[ 'country' => "CR", 'tel' => "506", 'name' => "Costa Rica" ],
	[ 'country' => "HR", 'tel' => "385", 'name' => "Croatia" ],
	[ 'country' => "CU", 'tel' => "53", 'name' => "Cuba" ],
	[ 'country' => "CY", 'tel' => "90", 'name' => "Cyprus - North" ],
	[ 'country' => "CY", 'tel' => "357", 'name' => "Cyprus - South" ],
	[ 'country' => "CZ", 'tel' => "420", 'name' => "Czech Republic" ],
	[ 'country' => "DK", 'tel' => "45", 'name' => "Denmark" ],
	[ 'country' => "DJ", 'tel' => "253", 'name' => "Djibouti" ],
	[ 'country' => "DM", 'tel' => "1809", 'name' => "Dominica" ],
	[ 'country' => "DO", 'tel' => "1809", 'name' => "Dominican Republic" ],
	[ 'country' => "EC", 'tel' => "593", 'name' => "Ecuador" ],
	[ 'country' => "EG", 'tel' => "20", 'name' => "Egypt" ],
	[ 'country' => "SV", 'tel' => "503", 'name' => "El Salvador" ],
	[ 'country' => "GQ", 'tel' => "240", 'name' => "Equatorial Guinea" ],
	[ 'country' => "ER", 'tel' => "291", 'name' => "Eritrea" ],
	[ 'country' => "EE", 'tel' => "372", 'name' => "Estonia" ],
	[ 'country' => "ET", 'tel' => "251", 'name' => "Ethiopia" ],
	[ 'country' => "FK", 'tel' => "500", 'name' => "Falkland Islands" ],
	[ 'country' => "FO", 'tel' => "298", 'name' => "Faroe Islands" ],
	[ 'country' => "FJ", 'tel' => "679", 'name' => "Fiji" ],
	[ 'country' => "FI", 'tel' => "358", 'name' => "Finland" ],
	[ 'country' => "FR", 'tel' => "33", 'name' => "France" ],
	[ 'country' => "GF", 'tel' => "594", 'name' => "French Guiana" ],
	[ 'country' => "PF", 'tel' => "689", 'name' => "French Polynesia" ],
	[ 'country' => "GA", 'tel' => "241", 'name' => "Gabon" ],
	[ 'country' => "GM", 'tel' => "220", 'name' => "Gambia" ],
	[ 'country' => "GE", 'tel' => "7880", 'name' => "Georgia" ],
	[ 'country' => "DE", 'tel' => "49", 'name' => "Germany" ],
	[ 'country' => "GH", 'tel' => "233", 'name' => "Ghana" ],
	[ 'country' => "GI", 'tel' => "350", 'name' => "Gibraltar" ],
	[ 'country' => "GR", 'tel' => "30", 'name' => "Greece" ],
	[ 'country' => "GL", 'tel' => "299", 'name' => "Greenland" ],
	[ 'country' => "GD", 'tel' => "1473", 'name' => "Grenada" ],
	[ 'country' => "GP", 'tel' => "590", 'name' => "Guadeloupe" ],
	[ 'country' => "GU", 'tel' => "671", 'name' => "Guam" ],
	[ 'country' => "GT", 'tel' => "502", 'name' => "Guatemala" ],
	[ 'country' => "GN", 'tel' => "224", 'name' => "Guinea" ],
	[ 'country' => "GW", 'tel' => "245", 'name' => "Guinea - Bissau" ],
	[ 'country' => "GY", 'tel' => "592", 'name' => "Guyana" ],
	[ 'country' => "HT", 'tel' => "509", 'name' => "Haiti" ],
	[ 'country' => "HN", 'tel' => "504", 'name' => "Honduras" ],
	[ 'country' => "HK", 'tel' => "852", 'name' => "Hong Kong" ],
	[ 'country' => "HU", 'tel' => "36", 'name' => "Hungary" ],
	[ 'country' => "IS", 'tel' => "354", 'name' => "Iceland" ],
	[ 'country' => "IN", 'tel' => "91", 'name' => "India" ],
	[ 'country' => "ID", 'tel' => "62", 'name' => "Indonesia" ],
	[ 'country' => "IQ", 'tel' => "964", 'name' => "Iraq" ],
	[ 'country' => "IR", 'tel' => "98", 'name' => "Iran" ],
	[ 'country' => "IE", 'tel' => "353", 'name' => "Ireland" ],
	[ 'country' => "IL", 'tel' => "972", 'name' => "Israel" ],
	[ 'country' => "IT", 'tel' => "39", 'name' => "Italy" ],
	[ 'country' => "JM", 'tel' => "1876", 'name' => "Jamaica" ],
	[ 'country' => "JP", 'tel' => "81", 'name' => "Japan" ],
	[ 'country' => "JO", 'tel' => "962", 'name' => "Jordan" ],
	[ 'country' => "KZ", 'tel' => "7", 'name' => "Kazakhstan" ],
	[ 'country' => "KE", 'tel' => "254", 'name' => "Kenya" ],
	[ 'country' => "KI", 'tel' => "686", 'name' => "Kiribati" ],
	[ 'country' => "KP", 'tel' => "850", 'name' => "Korea - North" ],
	[ 'country' => "KR", 'tel' => "82", 'name' => "Korea - South" ],
	[ 'country' => "KW", 'tel' => "965", 'name' => "Kuwait" ],
	[ 'country' => "KG", 'tel' => "996", 'name' => "Kyrgyzstan" ],
	[ 'country' => "LA", 'tel' => "856", 'name' => "Laos" ],
	[ 'country' => "LV", 'tel' => "371", 'name' => "Latvia" ],
	[ 'country' => "LB", 'tel' => "961", 'name' => "Lebanon" ],
	[ 'country' => "LS", 'tel' => "266", 'name' => "Lesotho" ],
	[ 'country' => "LR", 'tel' => "231", 'name' => "Liberia" ],
	[ 'country' => "LY", 'tel' => "218", 'name' => "Libya" ],
	[ 'country' => "LI", 'tel' => "417", 'name' => "Liechtenstein" ],
	[ 'country' => "LT", 'tel' => "370", 'name' => "Lithuania" ],
	[ 'country' => "LU", 'tel' => "352", 'name' => "Luxembourg" ],
	[ 'country' => "MO", 'tel' => "853", 'name' => "Macao" ],
	[ 'country' => "MK", 'tel' => "389", 'name' => "Macedonia" ],
	[ 'country' => "MG", 'tel' => "261", 'name' => "Madagascar" ],
	[ 'country' => "MW", 'tel' => "265", 'name' => "Malawi" ],
	[ 'country' => "MY", 'tel' => "60", 'name' => "Malaysia" ],
	[ 'country' => "MV", 'tel' => "960", 'name' => "Maldives" ],
	[ 'country' => "ML", 'tel' => "223", 'name' => "Mali" ],
	[ 'country' => "MT", 'tel' => "356", 'name' => "Malta" ],
	[ 'country' => "MH", 'tel' => "692", 'name' => "Marshall Islands" ],
	[ 'country' => "MQ", 'tel' => "596", 'name' => "Martinique" ],
	[ 'country' => "MR", 'tel' => "222", 'name' => "Mauritania" ],
	[ 'country' => "YT", 'tel' => "269", 'name' => "Mayotte" ],
	[ 'country' => "MX", 'tel' => "52", 'name' => "Mexico" ],
	[ 'country' => "FM", 'tel' => "691", 'name' => "Micronesia" ],
	[ 'country' => "MD", 'tel' => "373", 'name' => "Moldova" ],
	[ 'country' => "MC", 'tel' => "377", 'name' => "Monaco" ],
	[ 'country' => "MN", 'tel' => "976", 'name' => "Mongolia" ],
	[ 'country' => "MS", 'tel' => "1664", 'name' => "Montserrat" ],
	[ 'country' => "MA", 'tel' => "212", 'name' => "Morocco" ],
	[ 'country' => "MZ", 'tel' => "258", 'name' => "Mozambique" ],
	[ 'country' => "MN", 'tel' => "95", 'name' => "Myanmar" ],
	[ 'country' => "NA", 'tel' => "264", 'name' => "Namibia" ],
	[ 'country' => "NR", 'tel' => "674", 'name' => "Nauru" ],
	[ 'country' => "NP", 'tel' => "977", 'name' => "Nepal" ],
	[ 'country' => "NL", 'tel' => "31", 'name' => "Netherlands" ],
	[ 'country' => "NC", 'tel' => "687", 'name' => "New Caledonia" ],
	[ 'country' => "NZ", 'tel' => "64", 'name' => "New Zealand" ],
	[ 'country' => "NI", 'tel' => "505", 'name' => "Nicaragua" ],
	[ 'country' => "NE", 'tel' => "227", 'name' => "Niger" ],
	[ 'country' => "NG", 'tel' => "234", 'name' => "Nigeria" ],
	[ 'country' => "NU", 'tel' => "683", 'name' => "Niue" ],
	[ 'country' => "NF", 'tel' => "672", 'name' => "Norfolk Islands" ],
	[ 'country' => "NP", 'tel' => "670", 'name' => "Northern Marianas" ],
	[ 'country' => "NO", 'tel' => "47", 'name' => "Norway" ],
	[ 'country' => "OM", 'tel' => "968", 'name' => "Oman" ],
	[ 'country' => "PK", 'tel' => "92", 'name' => "Pakistan" ],
	[ 'country' => "PW", 'tel' => "680", 'name' => "Palau" ],
	[ 'country' => "PA", 'tel' => "507", 'name' => "Panama" ],
	[ 'country' => "PG", 'tel' => "675", 'name' => "Papua New Guinea" ],
	[ 'country' => "PY", 'tel' => "595", 'name' => "Paraguay" ],
	[ 'country' => "PE", 'tel' => "51", 'name' => "Peru" ],
	[ 'country' => "PH", 'tel' => "63", 'name' => "Philippines" ],
	[ 'country' => "PL", 'tel' => "48", 'name' => "Poland" ],
	[ 'country' => "PT", 'tel' => "351", 'name' => "Portugal" ],
	[ 'country' => "PR", 'tel' => "1787", 'name' => "Puerto Rico" ],
	[ 'country' => "QA", 'tel' => "974", 'name' => "Qatar" ],
	[ 'country' => "RE", 'tel' => "262", 'name' => "Reunion" ],
	[ 'country' => "RO", 'tel' => "40", 'name' => "Romania" ],
	[ 'country' => "RU", 'tel' => "7", 'name' => "Russia" ],
	[ 'country' => "RW", 'tel' => "250", 'name' => "Rwanda" ],
	[ 'country' => "SM", 'tel' => "378", 'name' => "San Marino" ],
	[ 'country' => "ST", 'tel' => "239", 'name' => "Sao Tome & Principe" ],
	[ 'country' => "SA", 'tel' => "966", 'name' => "Saudi Arabia" ],
	[ 'country' => "SN", 'tel' => "221", 'name' => "Senegal" ],
	[ 'country' => "CS", 'tel' => "381", 'name' => "Serbia" ],
	[ 'country' => "SC", 'tel' => "248", 'name' => "Seychelles" ],
	[ 'country' => "SL", 'tel' => "232", 'name' => "Sierra Leone" ],
	[ 'country' => "SG", 'tel' => "65", 'name' => "Singapore" ],
	[ 'country' => "SK", 'tel' => "421", 'name' => "Slovak Republic" ],
	[ 'country' => "SI", 'tel' => "386", 'name' => "Slovenia" ],
	[ 'country' => "SB", 'tel' => "677", 'name' => "Solomon Islands" ],
	[ 'country' => "SO", 'tel' => "252", 'name' => "Somalia" ],
	[ 'country' => "ZA", 'tel' => "27", 'name' => "South Africa" ],
	[ 'country' => "ES", 'tel' => "34", 'name' => "Spain" ],
	[ 'country' => "LK", 'tel' => "94", 'name' => "Sri Lanka" ],
	[ 'country' => "SH", 'tel' => "290", 'name' => "St. Helena" ],
	[ 'country' => "KN", 'tel' => "1869", 'name' => "St. Kitts" ],
	[ 'country' => "SC", 'tel' => "1758", 'name' => "St. Lucia" ],
	[ 'country' => "SR", 'tel' => "597", 'name' => "Suriname" ],
	[ 'country' => "SD", 'tel' => "249", 'name' => "Sudan" ],
	[ 'country' => "SZ", 'tel' => "268", 'name' => "Swaziland" ],
	[ 'country' => "SE", 'tel' => "46", 'name' => "Sweden" ],
	[ 'country' => "CH", 'tel' => "41", 'name' => "Switzerland" ],
	[ 'country' => "SY", 'tel' => "963", 'name' => "Syria" ],
	[ 'country' => "TW", 'tel' => "886", 'name' => "Taiwan" ],
	[ 'country' => "TJ", 'tel' => "992", 'name' => "Tajikistan" ],
	[ 'country' => "TH", 'tel' => "66", 'name' => "Thailand" ],
	[ 'country' => "TG", 'tel' => "228", 'name' => "Togo" ],
	[ 'country' => "TO", 'tel' => "676", 'name' => "Tonga" ],
	[ 'country' => "TT", 'tel' => "1868", 'name' => "Trinidad & Tobago" ],
	[ 'country' => "TN", 'tel' => "216", 'name' => "Tunisia" ],
	[ 'country' => "TR", 'tel' => "90", 'name' => "Turkey" ],
	[ 'country' => "TM", 'tel' => "993", 'name' => "Turkmenistan" ],
	[ 'country' => "TC", 'tel' => "1649", 'name' => "Turks & Caicos Islands" ],
	[ 'country' => "TV", 'tel' => "688", 'name' => "Tuvalu" ],
	[ 'country' => "UG", 'tel' => "256", 'name' => "Uganda" ],
	[ 'country' => "GB", 'tel' => "44", 'name' => "UK" ],
	[ 'country' => "UA", 'tel' => "380", 'name' => "Ukraine" ],
	[ 'country' => "AE", 'tel' => "971", 'name' => "United Arab Emirates" ],
	[ 'country' => "US", 'tel' => "1", 'name' => "USA" ],
	[ 'country' => "UY", 'tel' => "598", 'name' => "Uruguay" ],
	[ 'country' => "UZ", 'tel' => "998", 'name' => "Uzbekistan" ],
	[ 'country' => "VU", 'tel' => "678", 'name' => "Vanuatu" ],
	[ 'country' => "VA", 'tel' => "379", 'name' => "Vatican City" ],
	[ 'country' => "VE", 'tel' => "58", 'name' => "Venezuela" ],
	[ 'country' => "VN", 'tel' => "84", 'name' => "Vietnam" ],
	[ 'country' => "VG", 'tel' => "1", 'name' => "Virgin Islands - British" ],
	[ 'country' => "VI", 'tel' => "1", 'name' => "Virgin Islands - US" ],
	[ 'country' => "WF", 'tel' => "681", 'name' => "Wallis & Futuna" ],
	[ 'country' => "YE", 'tel' => "969", 'name' => "Yemen (North)" ],
	[ 'country' => "YE", 'tel' => "967", 'name' => "Yemen (South)" ],
	[ 'country' => "ZM", 'tel' => "260", 'name' => "Zambia" ],
	[ 'country' => "ZW", 'tel' => "263", 'name' => "Zimbabwe" ],
	];
}
